---
deployment:
  tasks:
    - export DOCROOT=/home/quragkwh/laundrycatcher.youngmomins.com
    - export SRC=/home/quragkwh/repos/laundry-catcher/dist
    - /bin/mkdir -p $DOCROOT
    - /usr/bin/rsync -rlpt --delete --chmod=D755,F644 --exclude=/.well-known/ --exclude=/cgi-bin/ --exclude=/.ssl-manager/ --exclude=/error_log --exclude=/.htaccess.bk $SRC/ $DOCROOT/
    - /bin/chmod 755 $DOCROOT
    - /bin/echo "Deployed $(cd /home/quragkwh/repos/laundry-catcher && /usr/local/cpanel/3rdparty/bin/git rev-parse --short HEAD) to $DOCROOT at $(date)"
